
name: Visualisation with Datadog
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'

jobs:
  visual:
    name: visual
    runs-on: macos-11
    container:
      image: node:14.15.0-alpine3.12
    steps:
      - uses: actions/checkout@master
      - name: Docker compose
        run: docker-compose up -d
      - name: install k6
        run: brew install k6
      - name: install docker agent
        run: DOCKER_CONTENT_TRUST=1 \
             docker run -d \
              --name datadog \
              -v /var/run/docker.sock:/var/run/docker.sock:ro \
              -v /proc/:/host/proc/:ro \
              -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
              -e DD_SITE="datadoghq.com" \
              -e DD_API_KEY=${{ secrets.DATADOG }} \
              -e DD_DOGSTATSD_NON_LOCAL_TRAFFIC=1 \
              -p 8125:8125/udp \x
              datadog/agent:latest
      - name: run k6 script
        run: K6_STATSD_ENABLE_TAGS=true k6 run --out statsd spike.js
