name: container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    steps:
         - name: Login to Docker Hub
           uses: docker/login-action@v1
           with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
         - name: install docker
           run: docker pull loadimpact/k6
         - name: run docker agent
           run: docker run -d --name dd-agent -v /var/run/docker.sock:/var/run/docker.sock:ro -v /proc/:/host/proc/:ro -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro -e DD_API_KEY= ${{ secrets.DATADOG }} gcr.io/datadoghq/agent:7 
         - name: k6 
           run: |
             K6_STATSD_ENABLE_TAGS=true k6 run --out statsd spike.js
