name: container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: honesthacker/datadog:latest
    steps:
         - name: Log the node version
           run: |
             node -v
             cat /etc/os-release  
