name: container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: honesthacker/datadog:latest
    steps:
         - name: Log the node version
           run: |
             K6_STATSD_ENABLE_TAGS=true k6 run --out statsd spike.js
