name: docker

on:
  schedule:
     - cron: "0 0 * * *" 

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macos-11

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: k6 install
      run: brew install k6
    - name: pull docker
      run: |
        docker pull honesthacker/datadog:latest
    - name: run script
      run: k6 run smoke.js
  
