name: docker

on:
# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macos-11
    container: 
      image: honesthacker/datadog:latest
    steps:
       - name: install k6
         run: brew install k6
       - name: run k6 script
         run: K6_STATSD_ENABLE_TAGS=true k6 run --out statsd spike.js

    
