name: Visualisation with Datadog
on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
    
  push: 
    branches: "master"

jobs:
  visual:
    name: visual
    runs-on: macos-11
    steps:
      - uses: actions/checkout@master
      - name: install k6
        run: brew install k6
      - name: install docker agent
        run: DOCKER_CONTENT_TRUST=1 \
             docker run -d \
              --name datadog \
              -v /var/run/docker.sock:/var/run/docker.sock:ro \
              -v /proc/:/host/proc/:ro \
              -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
              -e DD_SITE="datadoghq.com" \
              -e DD_API_KEY=${{ secrets.DATADOG }} \
              -e DD_DOGSTATSD_NON_LOCAL_TRAFFIC=1 \
              -p 8125:8125/udp \x
              datadog/agent:latest
      - name: run k6 script
        run: K6_STATSD_ENABLE_TAGS=true k6 run --out statsd script.js
